name: Build and deploy ASP.NET Core app to Azure Web App - sabermais

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore
        run: dotnet restore ./src/SaberMais.sln

      - name: Build
        run: dotnet build ./src/SaberMais.sln --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./src/SaberMais.csproj -c Release -o ./publish

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: published-app
          path: ./publish

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: published-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B4734ED4CCBF4DAFA6723FD0EB454477 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_6A6563AB95A34BA0AA5DE1F65E1B6C80 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_9D87C6737D3449A9BD80993A298F4C3B }}


      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'sabermais'
          slot-name: 'Production'
          package: .


